### ISSUE TITLE
Convenience functions for transforming parameters

### ISSUE THREAD

**Issue by ben18785** [pints-team/pints#1070]
I have been using Stan in anger the past couple of days, which has been enlightening and also a little frustrating.

The reason for this frustration is that a lot of our methods (all sensitivity-based approaches, for example) do not play well in problems where parameters have constraints; that is, cases when there are boundaries beyond which the log-probability is infinite. Because of this, in using models with uniform priors, I have had methods throwing errors mid-sampling.

To increase the robustness and to simplify the introduction of future algorithms (because we don't need to worry about any boundary issues), I strongly suggest we do what Stan and PyMC3 do -- transform all parameters to be unconstrained and then do sampling on this transformed space. In addition to reducing potential bugs, there is theory that sampling is more efficient on the transformed space.

This is actually quite simple to do (at least statistically) and involves the following:

- Transform constrained parameters to unconstrained space (for uniform parameters, one way to do this is to transform to the unit interval then take the logit function)
- Add a Jacobian term to the log probability (and to the gradient, if necessary) that accounts for this transformation
- Sample on transformed space
- Transform samples back to their original (constrained) parameter space

I'm happy to do this and think it is a real priority as will reduce a whole host of bugs awaiting our users. My question is, how is best to do this @MichaelClerx @martinjrobins ? We could do something like:

- Before sampling occurs, all parameters are checked for whether they are bounded; this is recorded in some sort of class which has methods like: transformed(), istransformed(), untransform() and jacobian() which can be queried for each parameter
- When sampling starts, each time a function is evaluated the jacobian term is added to the log prob (and gradient if necessary)
- When sampling ends, we perform untransform() on all parameters where it is necessary

**Comment by MichaelClerx** [comment]
We'd have to think very very carefully about this. For the problems I've worked on the transform made a lot of difference, but had to be made in a very problem-specific way. For me that's outside the scope of PINTS; precisely the kind of thing a user (who understands the problem) should do before passing it off to PINTS

**Comment by MichaelClerx** [comment]
Had several discussions with Gary about this as well, see e.g. https://github.com/pints-team/pints/issues/31

My advice is still the same: Write a model wrapper around your forward model. See the example here https://github.com/pints-team/pints/blob/master/examples/optimisation/transformed-parameters.ipynb

This
- Gives the user full control over the transformation
- Is less work for the user than having to always implement transformations
- Stops us from having to update _all of pints_ to always expect transformations

**Comment by MichaelClerx** [comment]
Here's a published, complex, real-life example: https://github.com/CardiacModelling/FourWaysOfFitting/blob/master/python/fitting.py#L193-L198

**Comment by ben18785** [comment]
Fair enough. One thing you need to be mindful of though, is that users need to implement Jacobian transformations themselves if they do inference (your example would not be correct if, for example, you had used a GaussianLogPDF() rather than a SumOfSquares error). Users would forget to do this. This is extra work for the user, not less.

It’ll make samplers easier to implement since we don’t need to worry about boundaries.

I do think we should take heed of what other software has done here: they do it for a reason. The main one being that it tends to improve sampling performance across a large range of models.

Re: extra work, it’s not changes to all models. It’s just changes to the way problems work.

**Comment by MichaelClerx** [comment]
> Add a Jacobian term to the log probability (and to the gradient, if necessary) that accounts for this transformation

Could you explain this bit some more? For starters, what do you mean by a jacobian in this context?

If certain methods prefer to work with transformations, could we implement it just for them?

Also worth noting we don't have samplers with boundaries, only with priors, which you could set to 0 outside the bounds?

**Comment by ben18785** [comment]
Yep, sorry for the confusing language: I am using priors and boundaries
synonymously here.

Also, sorry for the Jacobian drop: this is basically to do with
integration. When you do a transformation of variables in an integral, you
need to use a Jacobian term to account for the change of measure. For
probability distributions, this is the same: if you transform variables and
sample on that transformed space, then you need to account for any
non-linearities in the transform to ensure that the integral of the
probability density still amounts to 1. Sorry for the utterly shameless
self-reference here, but I wrote about this in my book in a few different
places. If you just search for "Jacobian" in the index, there's a bit about
this there, if you can stomach my relatively shite prose, that is!

**Comment by ben18785** [comment]
More concretely, if you don't apply the Jacobian term, then your samples
will give a biased view of the true posterior. The degree of this bias
depends on how non-linear the transform is...

**Comment by martinjrobins** [comment]
This is tricky, as @MichaelClerx says this is really a model problem and therefore outside the scope of pints. Stan and PyMC3 can do this easily because they rigorously define the model, so there is information there about how to transform the parameters into unconstrained space. Pints has no idea what model it is being given, so how do we know how to transform the space?

I think pints should simply be an "inference engine", you give it a model and it samples from it. I think that we should be focusing on building interfaces with packages that allow you to write (and parameter transform) models, including Stan and PyMC3. I think it would be awesome if I could write a PDE model in pybamm, wrap it in a statistical model in Stan, then sample from it in pints :)

**Comment by ben18785** [comment]
Cool. You’ve both won me round.

In that case, I think we should have a few examples where we encourage users to transform their parameters to be unconstrained. (Also transforming all parameters to be similarly scales, like in machine learning, tends to speed the plough.) As a halfway house, we could even have convenience functions for doing this (that calculate the Jacobian).

**Comment by martinjrobins** [comment]
I've been trying to sample from the SHO using nuts. Its absolutely essential to sample from unconstrained space using this model, otherwise the stepsize and mass matrix tends to be tuned to whatever the maximum tree level you set. My feeling currently is that NUTS is useless for a real problem unless you are sampling from unconstrained space.

I'm now thinking that we could provide a "wrapper" for any pints LogPDF that transforms it to unconstrained space using the transforms supported by Stan (I've found Stan's transformations here: https://mc-stan.org/docs/2_18/reference-manual/variable-transforms-chapter.html). This wrapper would also have methods for transforming samples back to constrained space. The user would have to provide information on the parameters to this wrapper (e.g. parameter 0 is lower/upper bounded at x, or bounded between x...y).

**Comment by MichaelClerx** [comment]
If there are common transformations we can implement something like this:

```
class WobblyTransform(pints.ParameterTransform, pints.ForwardModelS1):
    def n_parameters():
      ...
```

and if these can be made generally useful then I see no reason not to provide them!

Slight issue with the above example: Should we have separate wrappers to extend Model and ModelS1 ?

**Comment by martinjrobins** [comment]
That sounds great @MichaelClerx. We could have a single wrapper that just checks whether it is passed a Model or a ModelS1? There would be a significant amount of overlap between the two

**Comment by MichaelClerx** [comment]
Yeah I'm just wondering if we've done any `if instance(S1) then do funky stuff`, which would mean we can only use S1 if it really is one

**Comment by martinjrobins** [comment]
can you check for the presence of an `evaluateS1` function, rather than `if instance(S1)`? That would make it more general

**Comment by MichaelClerx** [comment]
That's more pythonic, isn't it :D
(But then if we do that, why have 2 interfaces at all?)

**Comment by martinjrobins** [comment]
I would prefer requiring users to use the interfaces :)

**Comment by chonlei** [comment]
One thing I strongly agree with @ben18785 is the Jacobian bit, it's very easy to forget when doing sampling. Especially when switching from optimisation to sampling posterior...!

**Comment by MichaelClerx** [comment]
Discussed this in the meeting again, personally now swayed that a model wrapper might not be the best option, instead have a Transformation class you can pass to a controller. Class should be able to

- transform points in parameter space (bidirectional)
- transform estimated distributions?
- transform jacobians for methods that need it (which would get rid of S1 problem mentioned above?)

**Comment by MichaelClerx** [comment]
Here's another design:

First we define a bunch of general purpose wrappers:
```
class pints.TransformedModel(ForwardModel):
    def __init__(self, model, transform):
        ...
class pints.TransformedErrorMeasure(ForwardModel):
    def __init__(self, error, transform):
        ...
class pints.TransformedBoundaries()
etc.
```
these could be in `pints` or in e.g. `pints.wrappers`, as I don't expect users to use them directly (unless they want to, I guess).

Then define an interface:
```
class Transformation(object):
    def to_world(self, search_parameter):
        ...
    def to_search(self, world_parameter):
        ...
    def n_parameters(self):
```

then the `Controller` classes could handle it from there?
So you'd pass in e.g. `opt = pints.OptimisationController(error, x0, boundaries, MyTransformation())` and then the controller could wrap the appropriate wrappers around error and boundaries, transform x0 to search coordinates, and convert back to "world" coordinates for returning and logging

Question 1: Would we be able to also convert `sigma0` ??
Question 2: What should we call "world parameters"? I was calling them "model parameters" until I remembered controllers take errors/likelihoods, so don't need models per se

**Comment by chonlei** [comment]
Can we use something more straight forward like "original parameters" and "transformed parameters" or such like even though a bit dull...?

I was thinking what is the best way to add a Jacobian correction to the posterior? Because if we need to posterior in model(/world/original) parameter space, then we need to sample with the Jacobian adjustment term. Looking at @MichaelClerx 's way of passing it to the OptimisationController (`opt = pints.OptimisationController(error, x0, boundaries, MyTransformation())`), we can probably have something like `JacobianAdjustedLogPosterior(log_posterior, log_jacobian)` and in `pints.MCMCController()` we check the posterior is an instance of `JacobianAdjustedLogPosterior()` (instead of normal `LogPosterior()`) if a `Transformation` argument is passed to it?

**Comment by MichaelClerx** [comment]
That's a good point Chon!

where would the JacobianAdjustedLogPosterior method come from? Once wrappers are in place, I want everything to proceed exactly as in the unwrapped case, so that you never do `if transformation-used-ages-ago then special logic`, because that's almost guaranteed to cause bugs or massive headaches, or code that gets too complex to build on in the future :-)

**Comment by MichaelClerx** [comment]
So whatever solution we come up with, needs to look like either:

1. User defines model in the search coordinates
2. Everything proceeds as normal

or

1. User provides model in model space
2. User creates a wrapper around model so that `Simulate` first converts from search to model space
3. Everything proceeds as normal

(if the user defines a logpdf or something instead, then the same logic works)

or

1. User provides model in model space
2. Controller creates wrappers
3. Everything proceeds as normal
4. Except for output to screen, which de-transforms parameter values

If we can't have it so that 99% of PINTS is unaware that the transformation has been made then I don't think we should do it.

**Comment by chonlei** [comment]
> That's a good point Chon!
> 
> where would the JacobianAdjustedLogPosterior method come from? Once wrappers are in place, I want everything to proceed exactly as in the unwrapped case, so that you never do `if transformation-used-ages-ago then special logic`, because that's almost guaranteed to cause bugs or massive headaches, or code that gets too complex to build on in the future :-)

Yeah, in my mind this new `JacobianAdjustedLogPosterior` should be used the same way as the `LogPosterior` that we have. A good check is if an identity transformation (i.e. does literally nothing) then it just proceeds as normal.

Just take log-transformation as an example, I was thinking something like
```
class JacobianAdjustedLogPosterior(LogPosterior):
    """
    Returns log-posterior that is Jacobian adjusted for the parameter transformation.

    With model parameter `b` and distribution `p(b)`, consider a
    parameter transformation `a = f(b)`, then we have
        `p(a) = p(f^{-1}(a)) |d/da f^{-1}(a)|,`                              (1)
    where the absolute value term is the Jacobian adjustment. For
    log-posterior, we have
        `log(p(a)) = log(p(f^{-1}(a))) + log(|d/da f^{-1}(a)|).`             (2)
    So the input would be the log-posterior not yet adjusted `log(p(f^{-1}(a)))`
    and the log-Jacobian correction term `log(|d/da f^{-1}(a)|)` and return the
    corrected one.
    """
    def __init__(self, log_posterior, log_jacobian):
       self._log_posterior = log_posterior
       self._log_jacobian = log_jacobian
       ...

    def __call__(self, x):
        return self._log_posterior(x) + self._log_jacobian(x)


class LogJacobian(object):  # not a PDF...
    """
    Returns log-Jacobian adjusted for the parameter transformation.

    With model parameter `b` and distribution `p(b)`, consider a
    transformation `a = f(b)`, then we have
        `p(a) = p(f^{-1}(a)) |d/da f^{-1}(a)|,`                              (1)
    where the absolute value term is the Jacobian adjustment. For
    log-posterior, we have
        `log(p(a)) = log(p(f^{-1}(a))) + log(|d/da f^{-1}(a)|).`             (2)
    We want to return the term `log(|d/da f^{-1}(a)|)` for classes extend
    ``LogJacobian``.
    """
    def n_parameters(self):
        raise NotImplementedError

    def __call__(self, transformed_parameters):
        raise NotImplementedError


class LogTransformLogJacobian(LogJacobian):  # not a PDF...
    """
    Returns log-Jacobian adjusted for the log-transformation.

    With model parameter `b` and distribution `p(b)`, consider a
    transformation `a = f(b)`, then we have
        `p(a) = p(f^{-1}(a)) |d/da f^{-1}(a)|,`                              (1)
    where the absolute value term is the Jacobian adjustment. For
    log-posterior, we have
        `log(p(a)) = log(p(f^{-1}(a))) + log(|d/da f^{-1}(a)|).`             (2)

    For a log transformation `f(.) = log(.)`, and `f^{-1}(.) = exp(.)`. Then the
    Jacobian term is simply the exponential of the transformed parameters,
    `exp(a)`. Then the Jacobian adjustment of the log-posterior, the second term
    in Equation (2), for the log transformation becomes simply the transformed
    parameters `a`.
    """
    def __init__(self, n_parameters):
        self._n_parameters = n_parameters

    def n_parameters(self):
        raise self._n_parameters

    def __call__(self, transformed_parameters):
        return np.sum(transformed_parameters)
```

So the `pints.MCMCController()` should either be
`mcmc = pints.MCMCController(log_posterior, n_chains, x0)`
or
`mcmc = pints.MCMCController(jacobian_adjusted_log_posterior, n_chains, x0, MyTransformation())`
And inside the controller, since `jacobian_adjusted_log_posterior` should work just as if the normal `log_posterior`, all we need to do is to make sure the user has passed a `JacobianAdjustedLogPosterior` instance instead of a `LogPosterior` when `MyTransformation()` is provided at the beginning. The rest will remain the same -- so back to "Everything proceeds as normal".

**Comment by chonlei** [comment]
Or! We can make it more general to do `JacobianAdjustedPDF` instead! Because this adjustment is needed whenever a transformation is used for a PDF. So we should also check the user gives a Jacobian adjusted PDF whenever he/she tries to sample from it.

**Comment by MichaelClerx** [comment]
Ok, but then the user passes in `mcmc = pints.MCMCController(jacobian_adjusted_log_posterior, n_chains, x0, MyTransformation())`...

In my example this was:
`mcmc = pints.MCMCController(untransformed_thing, ..., transformation)`
and then the MCMCController would apply the transformation,
otherwise there's not much difference with the scenario where we just ask the user to do all the transforming _before_ setting up the problem.

So should we maybe make providing a jacobian part of the transformation class?

```
class Transformation(object):
  def to_search()
  def to_model()
  def log_jacobian():
```
?

**Comment by chonlei** [comment]
Ha, I think I got you wrong that you want the *user* to see "Everything proceeds as normal" rather than the code in Pints to have "Everything proceeds as normal"...!

The one that I propose is a bit like having the user to define "posterior = prior * likelihood", but here is "the_correct_posterior = posterior * Jacobian_correction"... and what we ensure in Pints is that the user is aware of that, they need an extra "Jacobian_correction" term. So it seems to that it's an OK level of things the user does.

But if you want to have `log_jacobian()` inside `Transformation` should be OK too, all we have to do is to update in the MCMCController somewhere that `log_posterior = self._log_posterior(x) * Transformation().log_jacobian(x)`. Except the code will no longer look like the maths equation, which we have for the "posterior = prior * likelihood" (and I really like it!).

**Comment by MichaelClerx** [comment]
Haha, I want them _both_ to see as little difference as possible. Otherwise PINTS isn't handling it, the user is handling it. And we already have the situation where the user handles it

**Comment by MichaelClerx** [comment]
Going back to the original problem:

> I strongly suggest we do what Stan and PyMC3 do -- transform all parameters to be unconstrained and then do sampling on this transformed space. In addition to reducing potential bugs, there is theory that sampling is more efficient on the transformed space.

I'm beginning to think those libraries can do it because they don't have a generic lots-of-methods set up like us. So unless we can do something really nice and clean, I think we could just leave it up to the user?

**Comment by chonlei** [comment]
Second thoughts, I think having
```
class Transformation(object):
  def to_search()
  def to_model()
  def log_jacobian()
  def n_parameters()
```
is better! Let's do that!

I was thinking we can provide as much as transformation that we know and we can implement in Pints, and the rest will leave up to the user. And providing a few like log, logit etc. can already deal with a lot of cases I think!

**Comment by chonlei** [comment]
I will give it a go first, see if I can do it in a clean way! Not sure yet! :smile:
