### ISSUE TITLE
Add random seed control in all routines

### ISSUE THREAD

**Issue by chonlei** [pints-team/pints#141]
We probably want some kind of control of the random seed in both optimisation and inference routines -- for user debug sake or for reproducibility.

**Comment by MichaelClerx** [comment]
We can just use numpy.random.seed

**Comment by MichaelClerx** [comment]
If no-one can think of reasons seeding numpy isn't enough, I'm going to close this ticket!

**Comment by MichaelClerx** [comment]
Doesn't work for CMA. Yes let's add this method to `Optimiser` and `MCMCSampler` and others

**Comment by MichaelClerx** [comment]
For parallel sampling and optimisation, it'd be good to have a different random seed in each subprocess. One easy way to do this would be to pick a seed (NumPy uses an unsigned 32 bit int) for subprocess 0, and then use `seed_0 + i` to seed each subprocess `i`.

(You _don't_ want to use random seeds, because then you run the risk of having two identical chains / optimisations, if you're using the same starting point!)

That would mean our interface to set a random seed would be `sampling.seed(int seed)` and `optimisation.seed(int seed)`.

Pros:
- single number (no array of length nchains)
Cons:
- funny constraints on input (0 <= seed < 2**32 - nchains)

I'm guessing it's quite rare to see with numbers of O(2**32) ?
Can anyone splot any subtleties I might be missing @martinjrobins @chonlei @mirams @ben18785 @sanmitraghosh ?

**Comment by MichaelClerx** [comment]
Hmmmmm http://www.math.sci.hiroshima-u.ac.jp/~m-mat/MT/DC/dgene.pdf
Not sure if this matters for us!

**Comment by MichaelClerx** [comment]
https://scicomp.stackexchange.com/questions/24916/how-do-i-reliably-generate-random-numbers-in-python-distributed-across-multiple

**Comment by MichaelClerx** [comment]
> Seeding NumPy doesn't work for CMA

Had a look at the source. Turns out pycma _does_ use numpy, but seeds the random generator (using `np.random.seed()` which asks the system for a good seed) unless you explicitly pass it a seed (in which case it uses that one).
That's an annoying way to do it!

**Comment by MichaelClerx** [comment]
There's a [python wrapper for dcmt](https://github.com/fjarri/python-dcmt) but trying to pip install it results in a gcc compilation error for me

```
    src/wrapper/pyrandom.c:224:10: fatal error: common.h: No such file or directory
     #include "common.h"
              ^~~~~~~~~~
    compilation terminated.
    error: command 'gcc' failed with exit status 1
```

**Comment by MichaelClerx** [comment]
Yay! This guy is working on it for numpy:

- https://github.com/bashtage/ng-numpy-randomstate
- https://github.com/numpy/numpy/issues/6967

**Comment by MichaelClerx** [comment]
I hope you all love getting emails, because I've just worked out none of this matters*

The two methods we have that support parallelisation are `Optimisation` and the `MCMCSampling`. They are implemented following this pattern:

```
for i in range(iterations):
    xs = samplers.ask()
    fs = evaluate(xs) # This might happen in parallel
    samplers.tell(fs)
```

Alternatively, if a multi-chain MCMC method is used the `MCMCSampling` method works like this:

```
for i in range(iterations):
    xs = sampler.ask()
    fs = evaluate(xs) # This might happen in parallel
    sampler.tell(fs)
```

The important thing to note here is that the randomness is always in `ask()`, which gets executed in a single process. So none of this stuff matters, and we can just seed with a single number...

Woops



*unless we get interested in modelling stochastic processes, in which case we'd have to provide some way for the user to seed the individual models. Perhaps we can add a note saying to avoid parallelisation for stochastic models for now.

**Comment by MichaelClerx** [comment]
So as an interface, it should be enough to just have `seed(int seed)`, with the constraint that `seed` can be converted to an integer in the range `[0, 2**32-1]` inclusive (see https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.seed.html#numpy.random.seed)

**Comment by MichaelClerx** [comment]
_Or_, we don't seed in Pints at all, and just allow people to do it via `np.random.seed()`.

To circumvent the issue that some libraries might seed numpy themselves (e.g. cma) or some libraries might not use numpy's random, we can seed those methods using a random number generated from numpy.random. This would still produce consistent output!
