### ISSUE TITLE
Can't reproduce Stochastic Degradation model: No module named 'pints.toy.stochastic'

### ISSUE THREAD

**Issue by elizavetasemenova** [pints-team/pints#1471]
Hi, I am trying to run this example: 

https://github.com/pints-team/pints/blob/master/examples/toy/model-stochastic-degradation.ipynb

and am getting an error at the imports level. `import pints` is fine, but `import pints.toy.stochastic` gives "ModuleNotFoundError: No module named 'pints.toy.stochastic". 

Any hints?

**Comment by elizavetasemenova** [comment]
Thanks @ben18785, my previous attempt was with Conda.

Following your route, getting the following: 

>>> pints.toy.stochastic
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'pints' has no attribute 'toy'

**Comment by MichaelClerx** [comment]
Hi @elizavetasemenova ,
The `pints.toy.stochastic` module is a recent addition that is not yet included in the official PINTS "release" on pypi (which is what you get when you type `pip install pints`.
The solution is to install from the repository, using the steps outlined by Ben above but with one important correction:

- clone PINTS repo into e.g. `pints`
- create a virtual environment via `python3 -m venv env` at the terminal then `source env/bin/activate` to activate it
- cd `pints` (or wherever you cloned it)
- `python3 -m pip install -e .` to install the local PINTS. The `-e` switch will also make it so that you can update your PINTS by simply updating the checked out repository
- `python` and then `import pints.toy.stochastic`

Alternatively you can skip the cloning step and install directly from github with: `pip install git+https://github.com/pints-team/pints.git`

**Comment by elizavetasemenova** [comment]
`pip install git+https://github.com/pints-team/pints.git` worked locally, and, correspondingly, `!pip install git+https://github.com/pints-team/pints.git` works on Google Colab. Thanks!
