### ISSUE TITLE
Settings of XNES

### ISSUE THREAD

**Issue by ldv1** [pints-team/pints#1480]
Hi,

Would you have an example (notebook?) showing how to change the various settings of XNES in an optimization, in particular the size of the population?
Thanks !

**Comment by MichaelClerx** [comment]
Hi @ldv1 , sorry for the very late response.
There is no good example notebook in this repo at the moment, but in brief you:

1. Create an [OptimisationController](https://pints.readthedocs.io/en/stable/optimisers/running.html#pints.OptimisationController) instead of using the `pints.optimise` method that the example notebooks show
2. Use the [OptimisationController.optimiser()](https://pints.readthedocs.io/en/stable/optimisers/running.html#pints.OptimisationController.optimiser) method to gain access to the underlying optimiser method (in your case xnes), and tweak its settings, e.g. https://pints.readthedocs.io/en/stable/optimisers/xnes.html#pints.XNES.set_population_size

**Comment by MichaelClerx** [comment]
To be handled as part of #1491
