### ISSUE TITLE
Investigate the use of GPUs to speed up sampling

### ISSUE THREAD

**Issue by ben18785** [pints-team/pints#178]
Does anyone know how easy this is to do from within Python? Chris Holmes has shown that it is possible to get speed ups of a couple of order of magnitudes by using GPUs: https://arxiv.org/pdf/0905.2441.pdf

I was thinking this might be on a branch not master, since many computers don't have usable GPU calculation... However, if we were able to do this, it would be really mega.

Looks like people are already thinking about this: http://ftp.stat.duke.edu/WorkingPapers/11-17.pdf and https://arxiv.org/pdf/1402.4089.pdf.

**Comment by MichaelClerx** [comment]
To get any benefit, you'd have to do the computationally expensive part on a GPU, and massively parallel.

I can only imagine this working in one of two ways:

Idea A requires;
1. Some method that benefits from getting say 100 samples every iteration (so not traditional MCMC, but CMA-ES fits in nicely, although I'm not sure if the benefits don't drop off after X samples per iteration, at one point its idea of the space will be "good enough")
2. A parallel forward model simulation on a GPU. For cell ephys models we can do this with Myokit, but we would need a new `ParallelForwardModel` interface where you say `model.simulation([[sets of parameter sets]]) --> [[array of times arrays]]`

Idea B requires:
1. A sampler that benefits from running multiple times in parallel (e.g. independent chains of an MCMC routine)
2. Some model evaluation of independent models (again, Myokit can do this, but this is a coincidence, in general I don't see why anyone would implement this).

A generalised version (where we do the GPU stuff) is currently not really feasible, especially since we _want_ the model to be separate / implemented by the user

**Comment by MichaelClerx** [comment]
Actually, one thing we already can do is run ephys optimisations in parallel using Myokit to evaluate models on the GPU. No idea if this will be faster or not, still haven't tried. Could be a fun project for a student though!

**Comment by MichaelClerx** [comment]
This can be done easily if methods work with an ask-and-tell interface, so closing this ticket! (See #132 #185)
