### ISSUE TITLE
Noise in plot in nested inference example

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#207]
The notebook `examples/inference-first-example.ipynb` contains the line

    observed_values_est = pints.noise.add_independent_noise(signal_values_est, sigma)

to make a plot of the predictions. But why are you adding noise here? (And why do we need a method for this, you can just use numpy!)

**Comment by ben18785** [comment]
Ok, it's a matter of preference, and can see both sides of the argument. I
created the add_independent_noise and similar functions to add correlated
noise because I think they are a. frequently used and b. particularly in
the case of correlated noise, they abstract away any complexities from the
user.

For the first inference example, however, am happy if you want to use
numpy. But can we perhaps compromise on keeping these functions in Pints? I
in particular will use them a lot.

I am adding noise to the predictions because in applied cases the data is
noisy (hence why we have a sampling distribution). If you try to fit to the
signal itself you'll run into issues where the sampling distribution
collapses to a value.

**Comment by MichaelClerx** [comment]
> I am adding noise to the predictions because in applied cases the data is noisy (hence why we have a sampling distribution). If you try to fit to the signal itself you'll run into issues where the sampling distribution collapses to a value.

I see that, but you add noise to the final plot (the predicted posterior)! Since these are model predictions I don't see why you'd add arbitrary noise to each!

**Comment by MichaelClerx** [comment]
> Ok, it's a matter of preference, and can see both sides of the argument. I created the add_independent_noise and similar functions to add correlated noise because I think they are a. frequently used and b. particularly in the case of correlated noise, they abstract away any complexities from the user. For the first inference example, however, am happy if you want to use numpy. But can we perhaps compromise on keeping these functions in Pints? I in particular will use them a lot.

For the AR1 noise I completely see your point (although I'm wondering if we shouldn't just have noise _generators_, rather than _adders_, seems more general, no?). I'm only bringing this up because I'm very worried about "feature creep": Every new function (or parameter to a function) is something we need to maintain, test, document, rewrite when we're rewriting stuff... So just want to double-check all these decisions :-)

**Comment by ben18785** [comment]
Yeah you might be right -- noise generators is better!

No I completely get your hesitance with this stuff. I guess I am just quite
liberal with my use of functions!

**Comment by MichaelClerx** [comment]
Made a ticket for changing the adders to geneators: #222

But... still wondering why you were adding noise in this example (see above)
