### ISSUE TITLE
Add true parameters option to histogram / trace plots

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#267]
So need to change the signature from trace(chain1, chain2, ...) to trace([chain1, chain2, ...], reference=123)

Still not sure about the best name for the true parameters, see #263

**Comment by MichaelClerx** [comment]
Backwards incompatible so making it priority!

**Comment by chonlei** [comment]
So have we decided to *always* have `[chain1, chain2, ...]` as the return from _any_ MCMC? Even if we are running, say, just one chain, we return `[chain1]` instead of `chain1`?

**Comment by MichaelClerx** [comment]
Yup! (Except from the SingleChainMCMC lower level classes)
The reason being that you should never really do just one chain, in a real situation

**Comment by MichaelClerx** [comment]
Note also that the numpy equivalent of what you wrote could be

Array of shape (n_chains, n_samples)
Array of shape (1, n_samples)

So still easy to work with in the single chain case!

**Comment by MichaelClerx** [comment]
Thanks for looking into this Chon!

**Comment by chonlei** [comment]
@MichaelClerx Just thinking would it be problematic to have `samples` sometime refers to *one list of sampled points* e.g. in the `pints.plot.traces(samples)` and `pints.plot.pairwise(samples)` and sometime refers to *a list containing several lists of sampled pints* e.g. in histogram / trace due to the change here. 

The change from `chain` to `samples` is suggested here #249.

And it does not make sense to have "a list containing several lists of sampled pints" as the argument in traces / pairwise plots, because they only handle one list of sampled points.

**Comment by chonlei** [comment]
But probably okay, as long as it is clear in docs...?

**Comment by MichaelClerx** [comment]
Good point! We'll have to think about this!
