### ISSUE TITLE
Data based tests for log-likelihoods and log-priors

### ISSUE THREAD

**Issue by ben18785** [pints-team/pints#309]
Do we currently have tests for log-likelihoods that are based on data? For example, suppose our data X = (10.3,-9.5,3.2) => log Normal(X| 0.0 ,10.0) = -63.22. Do we do this sort of test? If not, I really think we need to. At the moment, it seems that we test that the dimensions of the problem are correct and for invalid constructors and a few other things.

For the log-priors, it seems that we have tests that are based on data for a few cases, but none that appear to test the exact quantiles of the distributions. For example, that log N(3| 0, 1) = -5.42.

The reason I am saying this is that it is conceivable that at some point someone may add new priors/adapt existing ones to handle new situations, in a way that doesn't set off the current tests. If people agree, I'd be happy to add a few tests. Was thinking of two quantile based tests (each exploring different regions) for each of the parameters.

**Comment by MichaelClerx** [comment]
Yup, we should really add a few!

Note that there's a `self.assertAlmostEqual(x, y)` method that you can use to get around numerical precision issues

**Comment by ben18785** [comment]
Cool, thanks! I'll create a branch and add a few tests.

**Comment by ben18785** [comment]
It looks like this is the case for the logistic (there is one test here that does what I want but not enough, in my view), Goodwin oscillator model, and so on. I really think we need to make it standard that all our tests actually test the simulated values (not just their shape and invalid constructors) versus a standard. Otherwise the models could be returning absolute garbage, that has the same shape as the correct output.

I'll put some values-based tests in the models, log-likelihoods and priors, but will probably need peoples' help with a few of the models.

**Comment by MichaelClerx** [comment]
How exactly would we test though? Just by checking visually once and then storing those values in a file?

**Comment by MichaelClerx** [comment]
Summary of discussion today:

1. We should create a separate repo for long-running "functional" tests. These differ in a few important ways. (A) They can be really, really long, are not run as often, and will probably run on a dedicated piece of equipment rather than a free service. (B) They can be stochastic. A "fail" might be alright, and just give us the data "Method X fails 5% of the time". (C) Unlike the unit tests, they can perform detailed (statistical) analysis of output.
2. As long as we have these, we can simplify the unit tests to tests that either (D) Do a single (fixed random seed) run of an algorithm that encounters all possible behaviours (e.g. accepting and rejecting for MCMC, switching into adaptive mode for adaptive MCMC, etc.), and then compare the output to a known, hard-coded data set. Or (E) Do multiple (fixed random seed) runs of algorithms with different settings (e.g. a run of adaptive MCMC in non-adaptive mode, a run in adaptive mode, etc.). For both D&E we could then make do with a low number of iterations (10?) so that the travis unit tests become a nice "Continuous" testing set.

**Comment by MichaelClerx** [comment]
I've set up a new pints-team repository at https://github.com/pints-team/functional-testing

**Comment by MichaelClerx** [comment]
See also #330

**Comment by MichaelClerx** [comment]
I think we pretty much have this now!
