### ISSUE TITLE
Rewrite "Results object" ideas as methods on the MCMCController

### ISSUE THREAD

**Issue by ben18785** [pints-team/pints#329]
I am opening up this can of worms again, sorry. 

After reflecting on this, I now agree with Michael that it's probably best to return just a numpy array as a result of sampling. 

I do think, however, that it's still useful to have a sampling result object/table function that basically summarises the result of sampling, if a user calls it. This ranges from parameter quantiles, to R-hats (for MCMC only) to effective sample sizes (per second), to other things which are sampler dependent. This is standard in other software and I certainly find it useful and less cumbersome than histograms for many-parameter models.

I have my MCMC result object from before but am considering simplifying it as well as generalising it to other sampling methods (and making tests for it, sorry!).

**Comment by mirams** [comment]
Hmmmm, quite nice to be able to calculate ESS etc. on a results object rather than the MCMC thing itself, as you might want to manually thin the chain, discard more burn in, or something first. So it's not clear to me that you want these methods on the MCMCsampler rather than MCMCresults. An subclass of numpy array that had such methods might work, if practical?

**Comment by MichaelClerx** [comment]
Still think this should be done by adding methods to the Controller class to return anything we'd like to know. See #271

**Comment by MichaelClerx** [comment]
See also #862

**Comment by MichaelClerx** [comment]
Closed in #986
