### ISSUE TITLE
Differential Evolution advice on hyper-parameters

### ISSUE THREAD

**Issue by martinjrobins** [pints-team/pints#362]
The Differential Evolution MCMC has two hyper-parameters gamma and the normal scale coefficient. There should be some advice in the documentation (http://pints.readthedocs.io/en/latest/mcmc_samplers/differential_evolution_mcmc.html) on how to choose these, or what their minimum/maximum bounds are.

@ben18785

**Comment by ben18785** [comment]
@martinjrobins I have just re-read [this](http://edepot.wur.nl/26336) paper on which the algorithm I coded up was based. 

- This suggests that a good default for gamma = 2.38 / (2 * sqrt(self._dimension)). They also occasionally have a variant of the algorithm where every 10 iterations gamma is set to 1. This makes it easier for the chains to jump between modes. Would you mind if I added in this option? (This also suggests that gamma in [default, 1] is probably a good range to investigate.)

- In the paper they actually use a uniform distribution for the proposal although a normal distribution in the description; very confusing. They use e ~ U(-10^-4, 10^-4) whereas we currently are using e ~ N(0, b * x0) essentially. The default value of b we use is 0.01 but, if this doesn't work then we may want to lower it so that it is more like what they use (an equivalent standard deviation of the normal would be 0.0001, so perhaps the default is currently too high).

Alternatively, we may want to allow the user to directly specify either e ~ U(-b, b) or  e ~ N(0, b) so that we avoid the complication with x0 and allows the user to more directly set the parameters.

I'm happy to make these changes to give us/the user more freedom in benchmarking but I don't want to make inordinately more work for you. What do you think?

Also, some over stuff I wanted to check about benchmarking:

- Are we using more chains than dimensions? In simulations they investigate performance from n_chains = 2 * _dimensions to 10 * _dimensions. I would actually prefer it if we set a default number of chains as twice the number of dimensions and prevent anything lower than, say, 1.5 * _dimensions. How would you feel about this change?

- How are we initialising the chains? This algorithm depends crucially on the chains _not_ being started at the same point in parameter space. If they do, then I know the algorithm fails.

**Comment by martinjrobins** [comment]
I'm happy if you make these changes. Adding extra hyper-parameters for the problem isn't much more work for me, I just add another hyper-parameter to the optimisation. 

With the benchmarking, we currently use 3 chains for all methods, so it sounds like this would be insufficient. Do you think that the number of chains should be another hyper-parameter to optimise?

I initialise each chain randomly over the search space (i.e. randomly between the lower and upper bounds)

**Comment by ben18785** [comment]
@MichaelClerx Sounds good -- I'll add a warning.

@martinjrobins Yes, I think for the multiple chain methods we should be optimising over the number of chains as this is essentially a hyperparameter of these methods. With the single chain methods, it isn't really as the chains don't interact.

I'll make these changes then create a PR.

**Comment by martinjrobins** [comment]
note that if the number of chains is a hyper parameter than it should be set using the hyper-parameter interface.
