### ISSUE TITLE
Add simple method that plots 1d log-likelihoods near points in parameter space

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#42]

**Comment by MichaelClerx** [comment]
This would be a good diagnostic plot too. We could make it accept `ErrorMeasure` and `Likelihood` objects, and then for each parameter just do + or - 1%. Possibly something smarter like taking tiny steps and trying to get a certain percentage change in the output

**Comment by MichaelClerx** [comment]
If implemented, we could also change the `inference-first-example` to use this to plot the loglikelihood (instead of the current manual approach)

**Comment by mirams** [comment]
A very useful feature is this 1D line between two particular points. 

We do this a lot from the point in parameter space you end up at (p1 max posterior or max likelihood) to another particular point in parameter space (p2 e.g. the right answer that simulated synthetic data). With a bit of overshoot either side. e.g. a vector from p1-0.5(p1->p2) to p1+1.5(p1-p2). This is what Ross' plots of numerical tolerance effect are doing.

**Comment by MichaelClerx** [comment]
Yeah I'm thinking anything that has a `dimension()` method and is callable

**Comment by chonlei** [comment]
@mirams  I am not sure if it is that easy to combine what Micheal is suggesting and the 1D line between two particular points. So I separated them and made two methods instead (because both are useful!). The 1D line between two points is `log_likelihood_two_points(...)` and an example of it in [here](https://github.com/pints-team/pints/blob/4329f14b84d233985037dd0f690768c240d518c7/examples/optimisation-first-example.ipynb) -- I think it makes more sense to do it in the optimisation example than the inference one.

@MichaelClerx I think probably it is easier (and make more sense) to just ask the users to specify the range (boundaries) to look at! It is in the `log_likelihood_1d(...)`. 

Also, I added `histogram` to do the manual plot in the inference example -- I think having a shorter script there can make people focus on the good things about MCMC and Pints (because if they want to know how to plot, just go to the plotting examples; whereas in that inference-first-example, just focus on inference).

**Comment by mirams** [comment]
Looks nice, I guess there should be an optional argument that says how many samples to take along the line?

**Comment by chonlei** [comment]
Yup, I have that called `n_eva` stands for number of evaluations -- maybe call it something else (?).

**Comment by MichaelClerx** [comment]
I was hoping you'd work out some sort of algorithm to plot a loglikelihood without having the user say what the limits on each parameter are! That's quite a bit of work for a high dimensional problem...

**Comment by mirams** [comment]
Not quite sure what you mean Michael? This is good for 'between two points'. User can fairly easily specify those two points as +/- whatever percentage in any parameter they are worried about. I think this will do until we have a motivation for something else?

**Comment by MichaelClerx** [comment]
For the 2 point one that's fine (although... would it not make more sense to draw a straight line in n-dimensional space and plot on that instead of doing it per parameter?)

But for the other plot, where we just try to show a log-likelihood, you now have to input a lower and upper point in every dimension. For Kylie's model that means specifying 9 lower and 9 upper boundaries

**Comment by mirams** [comment]
I thought we did have a line between two points in N-D space, have we got something else?

**Comment by chonlei** [comment]
Yes, we have one for drawing a line between two points in N-D space -- `log_likelihood_two_points`. Although it is not a good name, it evaluates the "likelihood" (whatever function input by the user, in the example I used score function instead of likelihood) along the vector from p1-0.25(p1->p2) to p1+1.25(p1->p2) for the two points p1, p2 input by the user.

We have another plot `log_likelihood_1d` which varies one parameter at a time, and that requires the user to give the boundaries or the MCMC chain (which we work out the sigma to define the boundaries). I think we could also give a default one to use +/- 10% (but there is a down size of it -- what if it is zero as the input parameter?). And if we have something too fancy to do this simple plot, we might lose our intention of doing this kind of simple plots? (I guess there can easily be an exception to say why one particular algorithm is not good, e.g. evaluation time or the input parameters are not good etc.?)

**Comment by MichaelClerx** [comment]
They're all in!
