### ISSUE TITLE
Replace guts of multinest (and other expensive routines) with optimised c++

### ISSUE THREAD

**Issue by ben18785** [pints-team/pints#482]
For some of the expensive operations in the samplers (like the various bits of multinest) only.

Not sure what this would do re: users (we don't want them having to compile stuff) but thought it is worth considering for Pints 2.0+.

My main reason for suggesting this is that - eventually - due to the breadth of algorithms Pints has, people with forward problems that are non-expensive to compute may want to use our software. Then, efficiency vs other implementations becomes a key consideration.

**Comment by martinjrobins** [comment]
This is probably relevant for #469 and #433 as well, which might need models that are called every timestep (rather than models that return the entire time trace), and hence are much quicker to evaluate. I think we'll have to go down the c++ route eventually, but need to think about how to make it easiest for a user

**Comment by ben18785** [comment]
I agree with pretty much everything you say @MichaelClerx. There's loads we can do before considering any c++ implementations. My main reason for opening this issue is that I am pretty unsure that much of the algorithms I code (due to my ineptitude) is likely inefficient.

I also made these comments with a view to Pints in the future where it may be used for non-hard-time-series-type problems, which are cheap to compute but the posteriors are extremely pathological (lots of disconnected modes, etc.). In this setting, performance matters. As I said, this is very much in the future but wanted to raise it now so we (particularly me) have efficiency in mind. It's easy to think that since for our problems the forward problem takes the bulk of computational time, that the details of the implementation don't matter much.

**Comment by martinjrobins** [comment]
Agreed, this is an issue for the future and we would have to identify a pretty pressing need for C++ before we integrate it, as it will complicate the pints structure/installation enormously.

**Comment by MichaelClerx** [comment]
Installation issues can be solved by the way, if we start distribution via `pip` so that people can download precompiled binaries (presuming we don't need on-the-fly compilation). But that does still mean developers need a compiler!

**Comment by martinjrobins** [comment]
Yea, I was thinking it mainly complicates it (the installation) for us, since we have to setup everything up so it doesn't complicate things for the user :)

But I wasn't actually thinking of using C++ for the methods we have now, I'm actually pretty happy with our current assumption that the model is expensive, I think most (non-toy) models are. My main thinking was it *might* be necessary if we go down the State-space sampler route as in #469, since then model goes from "give me the entire time trace given a set of parameters theta" to "give me the next timestep based on the current state". The latter is probably going to be orders of magnitude cheaper to evaluate.

**Comment by MichaelClerx** [comment]
Closing this for now!
