### ISSUE TITLE
How to set attributes on a mcmc sampler

### ISSUE THREAD

**Issue by ben18785** [pints-team/pints#488]
I'm a bit confused. How do I set attributes on a given MCMC sampling object when it is called like,

mcmc = pints.MCMCSampling(log_pdf, 3, xs, method=pints.PopulationMCMC)

I can use mcmc.samplers() to return a list of three sampling objects whose attributes I can set separately, but I just want to change all of them (as I think someone would want to do pretty much all the time).  Is there a way to do this?

When instead I call the mcmc.sampler() method, I get an error 'The `sampler` method is not supported for single-sampler methods'.

This message is vague. What is a single sampler method? Do we mean a single chain method? Also, surely populationMCMC is a multiple chain method, no? It involves running multiple chains (each at different temperatures) simultaneously...

**Comment by MichaelClerx** [comment]
> I can use mcmc.samplers() to return a list of three sampling objects whose attributes I can set separately, but I just want to change all of them (as I think someone would want to do pretty much all the time). Is there a way to do this?

Yeah we should probably provide a method to set it on all of them at once. I'll look into this!

> When instead I call the mcmc.sampler() method, I get an error 'The sampler method is not supported for single-sampler methods'. This message is vague.

Sorry!

> What is a single sampler method? Do we mean a single chain method? Also, surely populationMCMC is a multiple chain method, no? It involves running multiple chains (each at different temperatures) simultaneously...

We can change it to single-chain if you like. And yes that's the idea, you've called a function that only makes sense for single-chain methods, but the sampling object is using a multi-chain method so it returns an error instead.

**Comment by ben18785** [comment]
Yeah, think it should be single chain. It’d be good to change. Cheers!

**Comment by MichaelClerx** [comment]
I can think of three ways to allow the underlying sampler/optimiser methods to be called:

1. Make the users do it themselves. This is what we currently have (and probably will retain), but involves the user doing ugly things like `for sampler in sampling.samplers(): sampler.set_x(123)`

2. Add some sort of string based method: `sampling.set('x', 123)`. This will try to call the underlying samplers method `set_x(123)` and fail if it doesn't exist

3. Add some sort of magic method, so that calling `sampling.set_x(123)` will A. notice this method doesn't exist, B. check if it does exist in its samplers, and then C. call the samplers' set_x() method with 123

Both 2 and 3 are useful, but introduce undocumented functions

Thoughts / preferences @martinjrobins @ben18785  ?

**Comment by MichaelClerx** [comment]
Anyone? @martinjrobins @ben18785 ?

**Comment by martinjrobins** [comment]
I'm pretty happy typing `[sampler.set_x(123) for sampler in sampling.samplers()]` to be honest. Can we just improve the error message / documentation to make it clear that this is what users should do?

Otherwise happy to go with the magical option 3

**Comment by MichaelClerx** [comment]
I'll focus on improving the error messages then!

**Comment by MichaelClerx** [comment]
@ben18785 How is this? https://github.com/pints-team/pints/pull/532
