### ISSUE TITLE
optimising ess when the number of chains is a hyper-parameter

### ISSUE THREAD

**Issue by martinjrobins** [pints-team/pints#511]
I'm changing the performance-testing (i.e. the methods/model matrix) so that the number of chains is also one of the hyper-parameters to be optimised (within the bounds of 1.5*n_parameters -> 10*n_parameters). 

The optimisation is done be maximising the ess, which is calculated via:
```python
ess = np.zeros(n_parameters)
for chain in chains:
   ess += pints._diagnostics.effective_sample_size(chain)
 ess = np.min(ess)
```

That is, it adds the ess from the different chains and then takes the minimum ess for each parameter as the finall ess value. Now that n_chains is a hyper-parameter, I'm thinking that I should take the *average* ess from the different chains instead, that is:

```python
ess = np.zeros(n_parameters)
for chain in chains:
   ess += pints._diagnostics.effective_sample_size(chain)
ess /= n_chains
ess = np.min(ess)
```
@ben18785, does this sound reasonable? I want to have an optimisation measure that is fair across all methods.

**Comment by ben18785** [comment]
Yep, that sounds like a good approach to me for the multiple chain methods.

The only thing I would say is that for single chain methods, it doesn’t make sense to have the number of chains as a hyper-parameter since the chains don’t interact. If you increase the number of chains here, you’ll just increase the number of chances to achieve a higher ESS.

**Comment by martinjrobins** [comment]
Yea, I was thinking that for many methods optimising the number of chains would just set it to the maximum. Is this a bad thing though, since we are comparing single-chain algorithms to multiple-chain algorithms, they should get the same amount of chains available to them?

**Comment by ben18785** [comment]
Errm. Yeah it's tricky. But with multiple chain methods, you get emergent
dynamics due to the interaction between the chains, whereas with single
chain methods this doesn't happen.

I think as long as we can quantify the methods in terms of "per function
evaluation" it should be fine.

Also, not sure if this is the place to mention it, but the nested sampling
algorithms also have ess calculations now.

**Comment by martinjrobins** [comment]
so perhaps that should be the optimisation "score": ess per total number of function evaluation? (where the ess is calculated by the average ess across the chains)

Great to hear the nested methods have ess calculations. How is this done, calling a member function of the sampler or using the normal `pints.effective_sample_size()` function?

**Comment by MichaelClerx** [comment]
So... Would it be easiest to just do a single chain for single-chain methods then? Since this shouldn't affect the result (one converged chain is as good as two), or the performance per evaluation etc. it seems like a waste of time to use more than 1
