### ISSUE TITLE
DreamMCMC failing functional testing for a normal distribution

### ISSUE THREAD

**Issue by martinjrobins** [pints-team/pints#527]
The DreamMCMC test is failing for a normal distribution. Most of the time it is fine, but the occasional run gives a bad KLD score. Can we improve the reliability of this method in some way? @ben18785

https://github.com/pints-team/functional-testing-results#mcmc_normal_dreammcmc_3

**Comment by martinjrobins** [comment]
note that the KLD plots for DreamMCMC look funny, very discontinuous with respect to iteration. Is this right?

**Comment by martinjrobins** [comment]
@MichaelClerx pointed out the the test is only using one chain (the first one) to calculate the KLD. Perhaps we should use **all** the chains?

**Comment by MichaelClerx** [comment]
@martinjrobins @ben18785 I've solved the mystery of the discontinuous jumps!

The code doesn't plot the KLD from iteration `0:i` as I thought (misremembered?), it plots the code for batches of 100 iterations. So for method that suddenly swap a chain, this will lead to discontinuities.

I think the reason I did this was because I expected it to still be gradually decreasing (as it does for adaptive covariance and the likes).

Am now updating the testing code to "weave" multiple chains together, which means we should get smooth curves for diff ev and dream at least. Still not for pop-mcmc, but I think that's ok! PopMCMC's _wants_ to upset the main chain regularly, to stop it from ignoring other modes...

**Comment by MichaelClerx** [comment]
I'm not sure what the current plots do. I'll try to create some kind of sliding window thing

**Comment by MichaelClerx** [comment]
(With "these plots", I mean the plots of KLD versus sample index, which are all posterior samples for nested...)

**Comment by MichaelClerx** [comment]
Have updated the plots and disabled egg box tests again.

Also noticed we don't provide the samplers with a sigma for these tests. Might work a lot better if we do?

**Comment by martinjrobins** [comment]
yea, happy to help out the samplers with a sigma

**Comment by MichaelClerx** [comment]
I've given them a prior (still no sigma!) now, just like the nested samplers use, and dream seems to do ok! Will have to wait a few days to see how well

**Comment by MichaelClerx** [comment]
DREAM seems to do ok now
