### ISSUE TITLE
Add score function 'RRMSE'?

### ISSUE THREAD

**Issue by chonlei** [pints-team/pints#590]
Sometime when I compare different output where the absolute magnitude does not really matter, I prefer to have a 'relative' RMSE score, which is simply `RMSE divided by RMSD of observed data to zero`. Maybe worth adding to PINTS?

**Comment by MichaelClerx** [comment]
I think it would be good to have!

Not because it'd improve the fitting (for a single problem it'd just be division by a constant), but because it might allow you to better compare fitting results for different data sets (e.g. different runs of the same experiment)

There _might_ also be situations where you'd use an RRMSE inside a [SumOfErrors](https://pints.readthedocs.io/en/latest/error_measures.html#pints.SumOfErrors) ?

**Comment by chonlei** [comment]
Yeah -- actually, _kind of_ a very handwavy automation for weighted sum of square error for a multi-output problem.

**Comment by MichaelClerx** [comment]
Hey @chonlei you have this lying around, right? Can you create a PR for it please?
