### ISSUE TITLE
Create mean functions for each log prior

### ISSUE THREAD

**Issue by ben18785** [pints-team/pints#737]
This makes it easier to check what parameterisation is implemented.

**Comment by MichaelClerx** [comment]
Happy to have a mean() method but don't understand the reasoning.

> This makes it easier to check what parameterisation is implemented.

Surely the docs should be very clear about this?

**Comment by fcooper8472** [comment]
This is true: the log priors now all have the expectation in the docstring.  This is fine, if people read the docs, but I can see the benefit to a user of being able to readily check their assumption about the parameterisation used.  Particularly in numpy/scipy there seem to be some interesting choices for parameterising distributions (see their [log normal](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.lognorm.html)!).

Because of the differences in parameterisation among different software packages, giving the user every opportunity to be able to check is probably good.  I imagine people doing something along the lines of

```python
p = GammaLogPrior(2., 4.)
assert(p.mean() == 8.)
```
And when the assertion fails they'll know we're using the other parameterisation.

**Comment by MichaelClerx** [comment]
Ok! As long as we give equations and exact descriptions of the parameters in the docstring
