### ISSUE TITLE
Pints function help

### ISSUE THREAD

**Issue by ben18785** [pints-team/pints#742]
Is there a way for a user to see the docstrings on a given function by typing?

If not, think this would be nice, and could work by something like:

function.help()

**Comment by MichaelClerx** [comment]
```
$ python
>>> import pints
>>> help(pints)
>>> help(pints.LogPDF)
```

**Comment by ben18785** [comment]
Is this in any of the example notebooks? If not, I suspect no one (me included) will know about. Can we reopen this and add an example of using this to a few notebooks.

**Comment by MichaelClerx** [comment]
We can discuss this, but I'm strongly against this. The reason is this is very basic python functionality, and is discussed in 100s of books and tutorials.

Even here:
```
[michael@laptop pints]$ python
Python 2.7.15 (default, Oct 15 2018, 15:24:06) 
[GCC 8.1.1 20180712 (Red Hat 8.1.1-5)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> help
Type help() for interactive help, or help(object) for help about object
```

literally any time you start a shell it tells you to do this.

I think we need to focus our efforts on documenting the methods and the maths and intuition behind those methods

**Comment by MichaelClerx** [comment]
Maybe a constructive way to deal with this would be to add some kind of "before you begin" notebook?

*Remember there's a lot of information in CONTRIBUTING.md already*, including links to [Numpy for matlab users](https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html) (which mentions `help()`) and [How can R Users Learn Python for Data Science ?](https://www.hackerearth.com/blog/machine-learning/how-can-r-users-start-learning-python-for-data-science/).

I don't think we should be explaining python, numpy, scipy, or even that much maths/stats, but we could definitely make a big page (probably and .MD file rather than a notebook?) that links to tutorials etc. that we like

**Comment by MichaelClerx** [comment]
New issue for this:  #939
