### ISSUE TITLE
New rebased master is missing some previous merges!

### ISSUE THREAD

**Issue by ben18785** [pints-team/pints#746]
#728 in particular. @MichaelClerx can we please look at this somewhat urgently as I'm concerned that we are missing out on previous work.

I do think we need to be careful in the future about these sort of large changes. In particular, if we are going to make them, I think we need to work the same way as we did previously -- namely with a PR with reviewers.

**Comment by ben18785** [comment]
@MichaelClerx Happy to help with this as think we'll need to look through old PRs to check that nothing is being missed off.

**Comment by MichaelClerx** [comment]
Hi Ben, Thanks for noticing that.

Just to clarify a bit:

1. I removed the studies directory from master, and from master's history. The other branches still have the studies in them. One way of removing the studies from those branches is to rebase them onto master. (Rebasing is when you pick up a branch from a tree and graft it on somewhere else). (So master itself was never rebased)
2. If the other branches touched the studies directory in some way, this won't work and you need to do something else, e.g. Move the studies files to the new studies repo and then purge the studies from that branch's history.

Both operations can be tricky so happy to help.

(I've seen a few new PRs for rebased branches, not sure why that's necessary as usually github picks up on a rebasing? But if that's a way that works for us I'm happy!)

I do apologise for the way this went, I shouldn't have done it at the end of a busy day. Unfortunately it's not something you can do with PRs and reviews (as you're not merging anything into master, you're rewriting its history (stalin style) to remove references to files that fell out of favour).

Again, it's mostly my fault for some over-rigorous deleting on master, but a few things that I've learnt from this:

1. Don't do this stuff at the end of a day
2. Try and keep commits simple - touching as few files as possible
3. Try and keep branches simple - not touching any files that don't need to be changed
4. If you're unsure something should go in the repo and it's big - don't add it until you're sure it belongs there

Point 1 relates to me making a mess, point 2 and 3 relate to us trying to clean up that mess

**Comment by MichaelClerx** [comment]
@ben18785 I don't think we're missing any merges. See here: https://github.com/pints-team/pints/commits/master
The last one after the studies change is #728

**Comment by MichaelClerx** [comment]
@ben18785 I've also manually checked some of the files for changes from #728 and it seems to me they're all still there...

**Comment by ben18785** [comment]
Cool, thanks for checking this stuff Michael. Agreed that I don’t make this stuff easy by making commits so large!

Also, don’t fret over these sorts of things — I mess up all the time on Git!

Ok, will look through my/Fergus’s PR. It may be that I’m missing something.

A quick question (due to my naivety) - what’s the benefit of rebasing vs merging? Ie why not delete the studies then merge this?

**Comment by MichaelClerx** [comment]
Cheers @ben18785 

I didn't rebase anything! Instead, I asked git to go through `master`'s history, and delete studies anywhere it found it. I then "force pushed" this to github, so that github also has a master without the studies in them.
The advantage of this as opposed to deleting is that they no longer exist even in the history - thus making the filesize of the whole repo smaller. Looking back maybe that was overkill, this is usually something you do if confidential data accidentally ended up in a repo.

So at that point there was my master, and github's master - both without studies having ever existed - and all branches plus local versions of the repo on everybody else's machine.
So when git compares a branch to master, it sees that the branch has lots of history (related to the studies) that master doesn't have. That's why it thinks there are lots and lots of commits in all branches right now.

For branches that didn't make changes to studies, you can fix this situation by rebasing the branch from the old master to the new (history-rewritten) master. Merging at this point would re-introduce all the studies stuff into the new master.

For branches that _did_ touch studies, it's a bit trickier. I think the best solution there is to (ask me to) first copy the contents of the studies to the new repo (thus preserving them), and then performing the same history rewriting trick on that branch (thus purging all mention of studies having ever existed from that branch too). After that, you have to make some tiny commit to get github's PR system to re-evaluate the system and it'll then place the branching point (where the branch started diverging from master) at a much more recent time in history.

**Comment by MichaelClerx** [comment]
![woops](https://user-images.githubusercontent.com/517644/53353522-d3652700-391c-11e9-99d4-0f4008d62bf8.png)

^^^ That's how I _think_ it works

**Comment by ben18785** [comment]
Interesting, thanks Michael!

**Comment by MichaelClerx** [comment]
A good way to get an idea of what's going on is by using the "Network" tab on the "Insights" bit of github: https://github.com/pints-team/pints/network

Although at the moment that shows everything's in a bit of a state :D

**Comment by MichaelClerx** [comment]
Think this is pretty much OK now? Haven't heard anything for a while :-)
