### ISSUE TITLE
Fix value returned by `curve_fit`

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#761]
Docs say should be `xbest, fbest`, code returns `xbest`
I suggest we do what the doc says in this case

@martinjrobins @chonlei ?

**Comment by MichaelClerx** [comment]
Then again, maybe we don't care about `f` here? Still, better to keep the same interface everywhere?

https://github.com/pints-team/pints/blob/master/pints/_optimisers/__init__.py#L802

https://github.com/pints-team/pints/blob/master/pints/_optimisers/__init__.py#L838-L839

https://github.com/pints-team/pints/blob/master/pints/_optimisers/__init__.py#L880

**Comment by chonlei** [comment]
Hmm, since elsewhere, i.e. both `optimise` and `OptimisationController(...).run()` return `xbest, fbest`, I think having `curve_fit` returns the same would be better(?). 

https://github.com/pints-team/pints/blob/master/pints/_optimisers/__init__.py#L573
https://github.com/pints-team/pints/blob/master/pints/_optimisers/__init__.py#L742-L743

**Comment by MichaelClerx** [comment]
Prioritising: Should be easy enough
