### ISSUE TITLE
Start storing commit date in test results, use to order them

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#804]
Currently we're using the date the test was run, which is not necessarily helpful.

Date may need to be determined as max(pints commit date, pfunk commit date)

Make sure all dates are stored in result file

**Comment by MichaelClerx** [comment]
Doing this as part of #779

**Comment by MichaelClerx** [comment]
Probably best to store authored date and committed date (both available via [gitpython](https://gitpython.readthedocs.io/en/stable/tutorial.html#examining-references))

**Comment by iamleeg** [comment]
All of the relevant dates are stored in the database for both pints and pfunk repositories, in the pull request: https://github.com/pints-team/functional-testing/pull/10

However, I'm still using the _test run date_ as the primary key for the table. The reason is that it's much more likely that multiple runs test the same _commit_ than happen _within the same second_, and you're likely to want to analyse events where the same test of the same version of the software passes on one occasion and fails on another. Any visualisation etc. of test results by commit date is a UI thing that can be done in the UI, not in the database writer, I think.

**Comment by MichaelClerx** [comment]
We might run into some issue with the test run date when #815 is implemented though?

**Comment by iamleeg** [comment]
Ah, yes. So perhaps the test name and all of the dates need to be informative, and the primary key an arbitrary ID like an incrementing integer.

**Comment by MichaelClerx** [comment]
Sounds good!

**Comment by iamleeg** [comment]
I've made that change.

**Comment by MichaelClerx** [comment]
Thanks! I'll try to have a detailed look on Tuesday
