### ISSUE TITLE
Remove resultswriter/reader infra

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#826]
DB stuff seems to be working now, so might be a good time to re-evaluate how we're reading/writing. Current structure was not so much designed as "lets see if this works"-ed.

Example of how it could be different:

- Have some sort of ActiveRow TestResult object that you create and modify, possibly with a `commit()` or `sync()` method that reads/writes to DB.
- Have a static class to fetch results, where each method has some query inside that does useful stuff and returns a list of result objects that match some hard-coded criteria

**Comment by MichaelClerx** [comment]
Ideas @martinjrobins @iamleeg @fcooper8472 ?

**Comment by iamleeg** [comment]
What's currently there isn't far from ActiveRow:

 - combine reader and writer into a single class. Pass the primary key (the row ID) in the `__init__()`: if it's non-None, then use it, otherwise create a row and use that
 - there already is a `write()` method but it does nothing because every write currently commits its changes. This can be changed so that writes are explicit.

**Comment by MichaelClerx** [comment]
A scenario for writing would be:

1. Create a test result, enter basic data (outcome=running), send to DB
2. Finish running test, update DB with outcome of test

Scenarios for reading:
- Get all completed runs of test X, that have a KLD value, group (and sort) by (pfunk_commit, pints_commit) and return a nested list
- Like before, but with some selection based on times
- That kind of thing!

**Comment by MichaelClerx** [comment]
https://github.com/pints-team/functional-testing/issues/25
