### ISSUE TITLE
Tweak results database structure

### ISSUE THREAD

**Issue by fcooper8472** [pints-team/pints#835]
The database structure currently contains some information that is either redundant or doesn't need to be there.  I think as far as the results database goes, the less info that doesn't need to be there, the better.  Specific points:

- Do we need `pints_commit`, `pfunk_commit` AND a new item `commit_hashes` made up of those two with a slash between?
- Do we need `authored_date` AND `committed_date`?  These will likely never be different with our branch/PR model, and even if they were different I can't see any scenario where we would want `authored_date` rather than `committed_date`.
- Do we need commit messages in the results DB?  On the rare occasion that we need to investigate, we can look up the commit with the hash that's already stored.
- The two seeds should be merged into a single seed, particularly as there is no numpy documentation for what the `seed()` function actually does when given a list.
- Seed doesn't need to be a column in the database AND an entry in the json.

Recommendations:

1. Remove redundant `commit_hashes` entry
1. Remove both `authored_date` entries
1. Remove both commit messages
1. Merge both seeds into a single seed: `(rand + run_no) % UINT_MAX` or similar
1. Remove seed from the json entry

**Comment by MichaelClerx** [comment]
My thoughts:

- `commit_hashes` can probably go
- I like having both dates, unless we fully understand why/how/when they're different and what the consequences are. Seems best to keep this data, just in case we discover reasons we'd like it later
- Commit messages were introduced in case we mess up the history (like I did that time) --> this changes the commit history, and as a result the commits get new hashes (because they've changed!), so that the stored hashes no longer match the github ones. For stuff like this, which could conceivably happen again, the messages can help us sort things out
- Seeds: Yes let's just have the 1 now that you figured out how :-)
- Agreed seed doesn't need to be in JSON

**Comment by fcooper8472** [comment]
Ok, new recommendations:

- [ ] Remove redundant commit_hashes entry 
- [ ] Merge both seeds into a single seed
- [ ] Remove seed from the json entry

This is all implemented in https://github.com/pints-team/functional-testing/pull/19. The last one we get for free: the seed was only in the json entry because `seed` was no longer a row (it was replaced by `seed_1` and `seed_2`.
