### ISSUE TITLE
Allow individual MCMC branches to return None (when others return samples)

### ISSUE THREAD

**Issue by lorcandelaney** [pints-team/pints#864]
In the pints/_mcmc/init.py, in the run() method, specifically in line 564, there's a check that ensures that the three chains all return a sample or "None" for intermediate steps. However, this check does not work well with slice samplers, since it is not possible to predict the number of intermediate steps required in an iteration of a single chain. As a result, it is inevitable to have some chains returning "None" while others return a sample in the same MCMC iteration. I believe that we might need to change the check in order to use the MCMCController for slice sampling.

**Comment by MichaelClerx** [comment]
Sample implementation by @lorcandelaney here: https://github.com/pints-team/pints/blob/c4fcd6f0f78e3eca2e9d72bc40cdc2f9a70209f1/pints/_mcmc/__init__.py#L550-L575

**Comment by MichaelClerx** [comment]
I'm not averse to having something like this. As far as I can remember it wasn't implemented at the time because we didn't need it.

However, the implementation will be a bit trickier than the code above I think, because we want it to be parallelised more efficiently for single chain samplers.

So the code (for single chain samplers) should probably do something like this :

* set all samplers to "active" state
* ask() each active sampler
* evaluate() the given samples
* tell() each active sampler
* store any new samples in some kind of buffer - it should be possible for some of the samplers to be several steps ahead of the others
* whenever the buffer has a sample for every chain, update the chains in memory, call the disk-logging methods etc.
* whenever any chain has the maximum number of samples, set it to inactivate: stop ask() telling for it

So the different samplers would run out-of-step with each other, but since they're all doing the same problem they should all take roughly the same number of iterations to reach N samples, over time.

**Comment by MichaelClerx** [comment]
Fixed in 2b74a3ce1467d88e715c8ad9fea02a9958692efa (See #882 )

**Comment by ben18785** [comment]
@lorcandelaney @MichaelClerx Can we close this now?
