### ISSUE TITLE
Add example of a custom model

### ISSUE THREAD

**Issue by MichaelClerx** [pints-team/pints#92]
This will be really useful!

Ideally do an ODE example (using scipy?)

**Comment by ben18785** [comment]
@MichaelClerx Looking really good -- a quick turnaround! Think this really helps in conveying how Pints works and its general utility. Thanks for doing this. My comments are relatively minor,

**'A system of ODES'**
- Under the system of ODEs, can we write the ODE equation explicitly (i.e. in maths form), and explain the reaction that it is modelling?
- Remove the ':' for 'Run an example simulation'. Sorry, pernickety but just trying to consistent with what follows.
- Can we add a y label to the plot of the solution of the ODE?

**'A system of ODEs with a Pints wrapper'**
- In the 'A system of ODEs with a Pints wrapper' section, can we make the parameters the same as above? I.e. [1,1] or below i.e. [5,3]. Think if we then add a note to the tune of, 'we obtain the same result as above or below [can you do cross referencing in Jupyter notebooks?]
- Similarly can we add axis labels to the plot?

**'An optimisation problem'**
- Can we add a little more description about what the 'optimisation problem' is? In other words, we are trying to minimise the squared deviation between the data and model to yield unique values of the parameters...just to make it clear what this approach doesn't yield -- a distribution of parameters. That's what MCMC or Frequentist routines do.
- Can we make the test parameters the same throughout the notebook. So whether it's [1,1] as above, or [5,3] (perhaps better because this yields two different parameter values)? I just think that'll make it flow a bit better...
- More of a development question, but can we make pints.snes (or any other optimisation routine) spit out column headings for the two things it prints. I.e. iteration and sum of squares in this example? I just think that makes it clearer to someone running this software.
- Similarly, is there a 'quiet' option for running the optimisation? In other words, can a user stop printing to the screen if they want to? I sometimes find this really useful if I'm running loads of models in MCMC.
- Can we add timing to the snes code in this Jupyter notebook? I think it would be useful for a user to know how long this optimisation took on someone's (i.e. your) machine, perhaps with a note about the PC's processors etc.
- Sorry, another development question, but is there a way to specify a convergence threshold to snes etc.? I.e. how much % change in the score is necessary for it to halt?
- Can we add axis labels to the graph here?

**More generally**
- Can we add paper references to SNES etc. (perhaps both the theory and the practical implementation) here and in the other examples we give? As someone who is not familiar with these routines, I'd like to have the opportunity to read about them.

**Comment by MichaelClerx** [comment]
I don't think we should do timing in the example, but agree with you on the other points!

**Comment by MichaelClerx** [comment]
There are `verbose` parameters (True/False) for the optimisers and MCMC method right now, but this will be replaced by something more general later (see #62)
