### ISSUE TITLE
Make functions within classes alphabetically ordered

### ISSUE THREAD

**Issue by ben18785** [pints-team/pints#943]

**Comment by martinjrobins** [comment]
any reason why? I'd be hesitant about adding a required code style that isn't an official pep8 thing (and thus automatically checked by things like flake8)

**Comment by MichaelClerx** [comment]
Well we've been doing it in most places anyway. The reasoning is that there's often no unambiguous way to order things "sensibly", and it makes stuff easier to find. But I'm quite happy to close this ticket and just do it for future stuff

**Comment by martinjrobins** [comment]
I'm not sure alphabetically makes sense in all contexts, I often group relevant functions together. e.g. dual averaging class groups functions relating to adapting the step size, and those adapting the mass matrix, and then another group for setters/getters.

**Comment by ben18785** [comment]
I've actually found the alphabeticising quite helpful in quite a few
places, to be honest.

**Comment by martinjrobins** [comment]
But it is more helpful to organise methods by how closely they are related to each other. For example, it makes more sense to group a setter and a getter for a particular hyperparameter together, since this pair of functions is conceptually interrelated, often you change one when you change the other. Similarly you want to keep all the hyperparameter setters/getters together so, for example, you can see at a glance what all the hyperparameters are. We often split algorithms for various sampler across two functions, `ask` and `tell`, so these should be together so you can read/edit both of these at the same time. 

Actually finding a particular function is a solved problem and is done automatically by your IDE, no need to force alphabetical ordering to do this.

**Comment by MichaelClerx** [comment]
Well we can drop it if you like. But then do something like this:

- if a file or list is already alphabetical, please add new entries alphabetically too
- if it's organised some other way, please try and go along with that
- don't go in and change files that are in order X to order Y, unless you're doing a massive rewrite

?

(And all of this is for code. Lists in rst files tend to affect the display order, and so should be organised in whatever way they help the user find things)

**Comment by martinjrobins** [comment]
yea, this makes reasonable, no sense in changing the ordering that already exists
